<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>App.WindowsService</RootNamespace>
    <OutputType>exe</OutputType>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PlatformTarget>x64</PlatformTarget>

    <!-- Spécifie explicitement le point d'entrée -->
    <StartupObject>App.WindowsService.Program</StartupObject>

    <!-- Publication en fichier unique si Release -->
    <PublishSingleFile Condition="'$(Configuration)'=='Release'">true</PublishSingleFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Management" Version="10.0.8" />
    <PackageReference Include="System.ServiceProcess.ServiceController" Version="7.0.0" />
  </ItemGroup>
</Project>